TASK1:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/VQA/
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23 # ! finetune取23；second pretrain，sep取30，sep+id取35...；answer text only的话取10...
  max_region_num: 100 # ! 原本是101，因为改了图像读取器，所以是37 = 1 + 36 先36，有一个处理的地方找不到了...
  batch_size: 128 # 原本是128
  eval_batch_size: 1024
  train_split: trainval
  val_split: minval
  lr: 0.00004 # ! 原本是 0.00004 finetune的时候不能改lr！！ 只有second pretrain才可以改
  num_epoch: 20 # ! 原本是20，现在调成6个epoch看看；second pretrain暂时调成2个epoch
TASK2:
  name: GenomeQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 2
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/visual_genome/
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/visual_genome/vg_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 26 # ! finetune取26；second pretrain取35...也即是35取sep
  max_region_num: 36 # ! 原本是101
  batch_size: 128 # original 128
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
TASK3:
  name: Visual7w
  type: V-logit-mc
  loss: BCEWithLogitLoss
  process: normal
  task_id: 4
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/visual7w
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/visual7w/visual7w_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /dvmm-filer3a/users/rui/multi-task/datasets/visual7w/visual7w_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 200
  batch_size: 256
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK4:
  name: RetrievalCOCO
  type: VL-logit
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 7
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/cocoRetreival
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: /dvmm-filer3a/users/rui/multi-task/datasets/cocoRetreival/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: /dvmm-filer3a/users/rui/multi-task/datasets/cocoRetreival/all_data_final_test_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 101
  batch_size: 128
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK5:
  name: RetrievalFlickr30k
  type: VL-logit
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k/flickr30k_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k/all_data_final_test_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 101
  batch_size: 128
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK6:
  name: refcoco
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 9
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco/refcoco_unc/refcoco_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco/refcoco_unc/refcoco_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 101
  batch_size: 256
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK7:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 10
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco/refcoco+_unc/refcoco+_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco/refcoco+_unc/refcoco+_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK8:
  name: refcocog
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 11
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco/refcocog_umd/refcocog_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /dvmm-filer3a/users/rui/multi-task/datasets/refcoco/refcocog_umd/refcocog_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 101
  batch_size: 256
  train_split: train
  val_split: val
  start_iteration: 0
  lr: 0.00002
  num_epoch: 20
TASK9:
  name: NLVR2
  type: VL-binary-classifier
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: /dvmm-filer3a/users/rui/multi-task/nlvr2
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/nlvr2/nlvr2_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 40
  max_region_num: 101
  batch_size: 64
  eval_batch_size: 512
  train_split: train
  val_split: dev
  lr: 0.00002
  num_epoch: 20
TASK10:
  name: VisualEntailment
  type: VL-tri-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 13
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/visual_entailment/
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k/flickr30k_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 56
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: dev
  lr: 0.00002
  num_epoch: 20
TASK11:
  name: GuessWhat
  type: VL-tri-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 14
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/guesswhat/
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 25
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: valid
  lr: 0.00004
  num_epoch: 20
TASK12:
  name: GQA
  type: VL-classifier-GQA
  loss: BCEWithLogitLoss
  process: normal
  task_id: 15
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/gqa/
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/gqa/gqa_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 26 # ! finetune取26；second pretrain取45... 就是45取sep
  max_region_num: 100 # ! 原本是101
  batch_size: 128 # original 128
  eval_batch_size: 1024
  train_split: trainval
  val_split: minval
  lr: 0.00004
  num_epoch: 20
TASK13:
  name: GuessWhatPointing
  type: V-logit-mc
  loss: BCEWithLogitLoss
  process: normal
  task_id: 17
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/guesswhat/
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /dvmm-filer3a/users/rui/multi-task/datasets/guesswhat/guesswhat_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 256
  max_region_num: 306
  batch_size: 64
  train_split: train
  val_split: valid
  lr: 0.00002
  num_epoch: 20
TASK14:
  name: FlickrGrounding
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 18
  dataroot: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k/
  features_h5path1: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k/flickr30k_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /dvmm-filer3a/users/rui/multi-task/datasets/flickr30k/flickr30k_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 24
  max_region_num: 200
  batch_size: 256
  train_split: train
  val_split: val
  lr: 0.000002
  num_epoch: 20
